INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title1','Text1', 1);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title2','Text2', 2);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title3','Text3', 3);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title4','Text4', 4);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title5','Text5', 1);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title6','Text6', 3);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title7','Text7', 4);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title8','Text8', 2);
INSERT INTO `news`(`title`, `text`, `fk_userId`) VALUES ('Title9','Text9', 1);
